version: '3'

services:

    app:
        container_name: app
        build:
            context: ./scienceorfiction
            dockerfile: dockerfile
        env_file:
            - ./scienceorfiction.env
            - ./secrets.env
        ports:
            - "80:80"
        volumes:
            - ./scienceorfiction/app:/scienceorfiction/app
        links:
            - db

    db:
        container_name: db
        image: mysql:8.0.18
        restart: always
        env_file:
            - ./scienceorfiction.env
            - ./secrets.env
        ports:
            - "3306:3306"
        expose:
            - "3306"
